version: 2.1
executors:
  build-android:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/T-Dynamos/SRAPS-App/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build-for-android:
    executor: build-android
    steps:
      - run: |
          sudo apt update
          sudo apt install python3
          sudo apt install -y git zip unzip openjdk-13-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.19 virtualenv  # the --user should be removed if you do this in a venv
          
          # add the following line at the end of your ~/.bashrc file
          export PATH=$PATH:~/.local/bin/
          git clone https://github.com/T-Dynamos/SRAPS-App ~/SRAPS-App
          cd ~/SRAPS-App
          BUILDOZER_WARN_ON_ROOT=0
          APP_ANDROID_ACCEPT_SDK_LICENSE=1
          sudo buildozer android debug
      - store_artifacts:
          path: ~/SRAPS-App/bin/srapsapp-2.02-armeabi-v7a-debug.apk
          destination: srapsapp-2.02-armeabi-v7a-debug.apk

workflows:
  build-android:
    jobs:
      - build-for-android
